= thesaurus
:toc:

image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro.poms/poms-thesaurus.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/poms/poms-thesaurus/]
image:https://img.shields.io/maven-central/v/nl.vpro.poms/poms-thesaurus.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:nl.vpro.poms%20AND%20a:poms-thesaurus]


== Thesaurus popup

=== Example

source code of the thesaurus frontend deployed in the NPO API.

This is deployed on link:https://rs.poms.omroep.nl/[rs.poms.omroep.nl] where it also has an link:https://rs.poms.omroep.nl/v1/thesaurus/example[example page]. This example page can be used to see how it works, and how it can be implemented.
But it boils down to:
[source,html]
----
  <script src="https://rs.poms.omroep.nl/v1/thesaurus/popup.js"></script>

  <script>
 gtaa.open(
     function (data) {
        // do stuff
     }, options
 );

</script>
----

== NPO API authentication

This also contains an implementation of the infamous NPO authentication. This can also be used separatedly as follows

In your `<head>`

[source,html]
----
  <script src="//cdnjs.cloudflare.com/ajax/libs/crypto-js/4.2.0/crypto-js.min.js" integrity="sha512-a+SUDuwNzXDvz4XrIcXHuCf089/iJAoN4lmrXJg18XnduKK6YlDHNRalv4yd1N40OKI80tFidF+rqTFKGPoWFQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://rs.poms.omroep.nl/v1/npo-api/authentication.js"></script>
  <script>
      var npoAuthentication = new NpoApiAuthentication('${param.apiKey}', '${param.apiSecret}');
  </script>
----
And then in javascript:

[source,js]
----

  var params =  {
     max: maxResults,
     schemes: 'names',
     text: text
   };
   var suggestionHeaders = {
      "x-origin": document.location.origin
   };
   var path = "thesaurus/concepts/"
   npoAuthentication.addAuthorizationHeader(suggestionHeaders, path, params);
   $http.get('/v1/api/' + path, {
     params: params,
     headers: suggestionHeaders
    }).then(function (response) {
 ...
----


== Implementations

Completely similarly, POMS also has a link:https://poms.omroep.nl/CMSSelector/example/[CMS Selector]
Known open source implementation of these are

- link:https://github.com/vpro/magnolia-vpro-ui?tab=readme-ov-file#poms-extensions[Magnolia] (used to be) in use @VPRO
- link:https://github.com/npo-poms/directus-cmsselector[directus] just a POC
- ..

And the idea was always that these could be completely analogically be extended to support the thesaurus too.


== Architecture

This popup works together with a few NPO api's. How it works exactly can be read link:https://github.com/npo-poms/poms-shared/tree/main/gtaa-openskos[here]
