---
name: build pull request

on:
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_ARGS: '--no-transfer-progress'
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
        cache: maven
    - name: Build with Maven
      run: mvn -B clean test

