---
name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    if: startsWith(github.ref, 'refs/heads/REL-')
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21
        server-id: central
        server-username: CENTRAL_USERNAME
        server-password: CENTRAL_PASSWORD
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        cache: maven
    - uses: oleksiyrudenko/gha-git-credentials@v2.1.2
      with:
        global: true
        name: 'github $GITHUB_ACTOR'
        email: 'poms@mmprogrami.nl'
        token: '${{ secrets.GITHUB_TOKEN  }}'
    - name: Release
      run: mvn -Pdeploy,central --batch-mode  -Darguments=-DskipTests  release:prepare release:perform
      env:
        CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}


